Added some files

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,41 +1,60 @@
 version: 2.1
 
+executors:
+  node:
+    docker:
+      - image: circleci/node:13.8.0
+  python:
+    docker:
+      - image: python:3.9.0-alpine
+  aws:
+    docker:
+      - image: amazon/aws-cli
+
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+      id:
+        type: string
     steps:
       - run:
-          name: Destroy environments
+          name: Destroy environment for backend cloudformation stack
           when: on_fail
           command: |
-            # Your code here
-            exit 1
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.id >>
+      - run:
+          name: Destroy environment for frontend cloudformation stack and s3
+          when: on_fail
+          command: |
+            aws s3 rm s3://udapeople-<< parameters.id >> --recursive
+            aws cloudformation delete-stack --stack-name udapeople-front-<< parameters.id >>
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      id:
+        type: string
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
-            if(( $SUCCESS==1 )); 
+            SUCCESS=$(curl "https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/migration_${CIRCLE_WORKFLOW_ID:0:7}")
+            echo "$SUCCESS"
+            if(( "$SUCCESS"=="success" )); 
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+              cd ~/project/backend
+              npm run migration:revert
+              echo "migrations have been reverted."
+            else 
+              echo "no migrations to revert."
             fi
             
 jobs:
   build-frontend:
-    docker:
-      - image: circleci/node:13.8.0
+    executor: node
     steps:
       - checkout
       - restore_cache:
@@ -43,229 +62,377 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            # Your code here
-            exit 1
+            cd frontend/
+            npm i
+            npm run build
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
 
   build-backend:
-    docker:
-      - image: circleci/node:13.8.0
+    executor: node
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-builder]
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+            ls -lah
+            pwd
+            cd backend/
+            npm i
+            npm run build
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-build
+          key: backend-builder
+      - persist_to_workspace:
+          root: .
+          paths:
+            - backend/dist
+            - backend/node_modules
 
   test-frontend:
-    docker:
-      # Docker image here
+    executor: node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Testing frontend
+          command: |
+            cd frontend/
+            npm run test
                 
   test-backend:
-    docker:
-      # Docker image here
+    executor: node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [backend-builder]
+      - run:
+          name: Testing backend
+          command: |
+            cd backend/
+            npm run test
             
   scan-frontend:
-    docker:
-      # Docker image here
+    executor: node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Scanning frontend
+          command: |
+            cd frontend/
+            npm audit fix --force
+            npm audit fix --audit-level=critical --force
+            npm audit --audit-level=critical
 
   scan-backend:
-    docker:
-      # Docker image here
+    executor: node
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [backend-builder]
+      - run:
+          name: Scanning backend
+          command: |
+            cd backend/
+            npm audit fix --audit-level=critical
+            npm audit --audit-level=critical
 
   deploy-infrastructure:
-    docker:
-      # Docker image here that supports AWS CLI
+    executor: aws
     steps:
-      # Checkout code from git
+      - checkout
+      - run:
+          name: Install tar utility
+          command: |
+            yum install -y tar gzip
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=udapeople \
+              --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --region us-east-1
+      - run:
+          name: Save the BACKEND_IP to rvdb
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:udapeople,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text) 
+            echo "${BACKEND_IP}"
+            curl "https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/backend_url_${CIRCLE_WORKFLOW_ID:0:7}" -d "${BACKEND_IP}"
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=udapeople \
+              --stack-name udapeople-front-${CIRCLE_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --region us-east-1
       - run:
           name: Add back-end ip to ansible inventory
+          working_directory: ./.circleci/ansible
           command: |
-            # Your code here
-            exit 1
+            echo "[all]" > inventory
+            aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:udapeople,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text >> inventory
       - persist_to_workspace:
-          root: ~/
+          root: .
           paths:
-            - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
+            - .circleci/ansible/inventory
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   configure-infrastructure:
-    docker:
-      # Docker image here that supports Ansible
+    executor: python
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - add_ssh_keys:
+          fingerprints: ["34:b8:83:88:95:73:32:a8:45:a2:fd:c0:2d:e5:95:a5"]
+      - attach_workspace:
+          at: .
       - run:
           name: Install dependencies
+          working_directory: ./.circleci/ansible
           command: |
-            # Your code here
-            exit 1
+            apk add --update ansible
+            ansible --version
       - run:
           name: Configure server
+          working_directory: ./.circleci/ansible
           command: |
-            # Your code here
-            exit 1
-      # Here's where you will add some code to rollback on failure      
+            pwd &&
+            ls -la
+            cat inventory
+            ansible-playbook -i inventory configure-server.yml -vvv
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}   
 
   run-migrations:
-    docker:
-      # Docker image here that supports NodeJS
+    executor: node
     steps:
-      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: .
+      - restore_cache:
+          keys: [backend-builder]
+      - run:
+          name: Install AWS CLI dependencies
+          command: |
+            sudo apt-get update && sudo apt-get install -yy less
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo apt-get dist-upgrade
+            sudo ./aws/install
+            sudo apt-get install libgnutls-openssl27
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
+            cd backend/
+            npm run migrations > migration_status
+            cat migration_status
       - run:
-          name: Send migration results to memstash
+          name: Send migration results to rxdb
           command: |
-            # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
-
+            cd backend/
+            if grep -q "has been executed successfully" migration_status
+            then
+              echo "DB migration was successful."
+              curl "https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/migration_${CIRCLE_WORKFLOW_ID:0:7}" -d 'success'
+            elif grep -q "No migrations are pending" migration_status
+            then
+              echo "No DB migrations needed."
+              curl "https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/migration_${CIRCLE_WORKFLOW_ID:0:7}" -d 'no_migrations_needed'
+            else
+              echo "DB migration failed, please verify setup! Probably the database already exists. Verify setup!"
+              curl "https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/migration_${CIRCLE_WORKFLOW_ID:0:7}" -d 'failure'
+            fi
+            echo "WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+  
   deploy-frontend:
-    docker:
-      # Docker image here that supports AWS CLI
+    executor: node
     steps:
-      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: .
+      - restore_cache:
+          keys: [frontend-build]
       - run:
           name: Install dependencies
+          working_directory: /tmp
           command: |
-            # your code here
+            sudo apt-get update && sudo apt-get install -yy less
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
       - run:
           name: Get backend url
+          working_directory: ./frontend
           command: |
-            # your code here
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:udapeople,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text)
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
+            npm run build
       - run:
-          name: Deploy frontend objects
+          name: Deploy frontend objects to S3
+          working_directory: ./frontend
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure      
-                    
+            aws s3 cp ./dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
+      - persist_to_workspace:
+          root: .
+          paths:
+            - frontend/dist   
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}    
+      - revert-migrations:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+
   deploy-backend:
-    docker:
-      # Docker image here that supports Ansible
+    executor: python
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - add_ssh_keys:
+          fingerprints: ["34:b8:83:88:95:73:32:a8:45:a2:fd:c0:2d:e5:95:a5"]
+      - attach_workspace:
+          at: .
       - run:
           name: Install dependencies
+          working_directory: ./.circleci/ansible
           command: |
-            # your code here
+            apk add --update ansible curl rsync openssh nodejs npm
+            ansible --version
       - run:
           name: Deploy backend
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            cd backend/
+            npm i
+            npm run build
+            cd ..
+            tar -C backend -czvf artifact.tar.gz .
 
+            ls -lah
+            pwd
+
+            cd .circleci/ansible/
+            cat inventory
+            ansible-playbook -i inventory deploy-backend.yml -vvv
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+  
   smoke-test:
-    docker:
-      # Lightweight Docker image 
+    executor: python
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
+          working_directory: /tmp
           command: |
-            # your code here
+            # yum install -y tar gzip
+            # yum install curl
+            
+            apk add --update curl nodejs npm
+            pip install awscli
+      - attach_workspace:
+          at: .
       - run:
-          name: Get backend url
-          command: |
-            # your code here
-      - run:
-          name: Backend smoke test.
-          command: |
-            # your code here
+          name: Backend smoke test
+          working_directory: ./backend
+          command: |            
+            BACKEND_IP=$(curl "https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/backend_url_${CIRCLE_WORKFLOW_ID:0:7}")
+            echo "${BACKEND_IP}"
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/index.html"
+            if curl -s ${URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      # - destroy-environment:
+          # id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+          # id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   cloudfront-update:
-    docker:
-      # Docker image here that supports AWS CLI
+    executor: aws
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            yum install -y tar gzip curl
+            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+            yum install -y nodejs
       - run:
           name: Update cloudfront distribution
+          working_directory: ./.circleci/files
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            aws cloudformation deploy \
+              --template-file cloudfront.yml \
+              --stack-name udapeople-cloudfront-production-${CIRCLE_WORKFLOW_ID:0:7} \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --tags project=udapeople
+      # - destroy-environment:
+          # id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+          # id: ${CIRCLE_WORKFLOW_ID:0:7}
 
-cleanup:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      - run:
-          name: Get old stack workflow id
-          command: |
-            # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
-      - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              # your code here
-            fi
-            
+  cleanup:
+      executor: aws
+      steps:
+        - checkout
+        - run:
+            name: Remove old stacks and files
+            command: |
+              OldWorkflowID="$(curl "https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/old_workflow")"
+              CurrentWorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
+              echo "$OldWorkflowID"
+              echo "Current workflow id $CurrentWorkflowID"
+              if [ "$CurrentWorkflowID" != "$OldWorkflowID" ];
+              then
+                echo "$OldWorkflowID!=$CurrentWorkflowID => will delete old version"
+
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                aws cloudformation delete-stack --stack-name "udapeople-front-${OldWorkflowID}"
+                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+                aws cloudformation delete-stack --stack-name "udapeople-cloudfront-production-${OldWorkflowID}"
+              else
+                echo "$OldWorkflowID==$CurrentWorkflowID => nothing needs to be done..."
+              fi
+              curl https://kvdb.io/E625cVBrW71Hwa4AJvDsg1/old_workflow -d "${CIRCLE_WORKFLOW_ID:0:7}"
 
 workflows:
   default:
     jobs:
+      # TODO - uncomment all
       - build-frontend
       - build-backend
       - test-frontend:
@@ -280,7 +447,7 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
             branches:
-              only: [test-feature-branch]
+              only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
